---
galaxy_info:
  author: "Katerina Koukiou"
  description: "Installs guest agents on VMs"
  company: "Red Hat"
  license: "GPLv3"
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - all
  galaxy_tags:
    - installer
